// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDoctrineMigrationVersion = "doctrine_migration_versions"

// DoctrineMigrationVersion mapped from table <doctrine_migration_versions>
type DoctrineMigrationVersion struct {
	Version       string    `gorm:"column:version;primaryKey" json:"version"`
	ExecutedAt    time.Time `gorm:"column:executed_at;default:NULL" json:"executed_at"`
	ExecutionTime int32     `gorm:"column:execution_time" json:"execution_time"`
}

// TableName DoctrineMigrationVersion's table name
func (*DoctrineMigrationVersion) TableName() string {
	return TableNameDoctrineMigrationVersion
}
