// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessengerMessage = "messenger_messages"

// MessengerMessage mapped from table <messenger_messages>
type MessengerMessage struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Body        string    `gorm:"column:body;not null" json:"body"`
	Headers     string    `gorm:"column:headers;not null" json:"headers"`
	QueueName   string    `gorm:"column:queue_name;not null" json:"queue_name"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;comment:(DC2Type:datetime_immutable)" json:"created_at"`         // (DC2Type:datetime_immutable)
	AvailableAt time.Time `gorm:"column:available_at;not null;comment:(DC2Type:datetime_immutable)" json:"available_at"`     // (DC2Type:datetime_immutable)
	DeliveredAt time.Time `gorm:"column:delivered_at;default:NULL;comment:(DC2Type:datetime_immutable)" json:"delivered_at"` // (DC2Type:datetime_immutable)
}

// TableName MessengerMessage's table name
func (*MessengerMessage) TableName() string {
	return TableNameMessengerMessage
}
