// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePax = "pax"

// Pax mapped from table <pax>
type Pax struct {
	ID        int32  `gorm:"column:id;primaryKey" json:"id"`
	FirstName string `gorm:"column:first_name;not null" json:"first_name"`
	LastName  string `gorm:"column:last_name;default:NULL" json:"last_name"`
	Role      string `gorm:"column:role;default:NULL" json:"role"`
}

// TableName Pax's table name
func (*Pax) TableName() string {
	return TableNamePax
}
