// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProperty = "property"

// Property mapped from table <property>
type Property struct {
	ID    int32 `gorm:"column:id;primaryKey" json:"id"`
	Value int64 `gorm:"column:value;not null" json:"value"`
	Ident int16 `gorm:"column:ident;not null" json:"ident"`
}

// TableName Property's table name
func (*Property) TableName() string {
	return TableNameProperty
}
