// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePropertyRecord = "property_record"

// PropertyRecord mapped from table <property_record>
type PropertyRecord struct {
	PropertyID int32 `gorm:"column:property_id;primaryKey" json:"property_id"`
	RecordID   int32 `gorm:"column:record_id;primaryKey" json:"record_id"`
}

// TableName PropertyRecord's table name
func (*PropertyRecord) TableName() string {
	return TableNamePropertyRecord
}
