// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTkMessage = "tk_message"

// TkMessage mapped from table <tk_message>
type TkMessage struct {
	ID      int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Imei    string `gorm:"column:imei;not null" json:"imei"`
	Message string `gorm:"column:message;not null" json:"message"`
}

// TableName TkMessage's table name
func (*TkMessage) TableName() string {
	return TableNameTkMessage
}
