// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTracker = "tracker"

// Tracker mapped from table <tracker>
type Tracker struct {
	ID   int32  `gorm:"column:id;primaryKey" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
	Imei string `gorm:"column:imei;not null" json:"imei"`
	Icon string `gorm:"column:icon;not null" json:"icon"`
}

// TableName Tracker's table name
func (*Tracker) TableName() string {
	return TableNameTracker
}
