// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTrip = "trip"

// Trip mapped from table <trip>
type Trip struct {
	ID            int32  `gorm:"column:id;primaryKey" json:"id"`
	RecordStartID int32  `gorm:"column:record_start_id;not null" json:"record_start_id"`
	RecordEndID   int32  `gorm:"column:record_end_id" json:"record_end_id"`
	Departure     string `gorm:"column:departure;default:NULL" json:"departure"`
	Arrival       string `gorm:"column:arrival;default:NULL" json:"arrival"`
	Comments      string `gorm:"column:comments;default:NULL" json:"comments"`
	Distance      int32  `gorm:"column:distance" json:"distance"`
	TrackerID     int32  `gorm:"column:tracker_id;not null" json:"tracker_id"`
}

// TableName Trip's table name
func (*Trip) TableName() string {
	return TableNameTrip
}
