// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTripPax = "trip_pax"

// TripPax mapped from table <trip_pax>
type TripPax struct {
	TripID int32 `gorm:"column:trip_id;primaryKey" json:"trip_id"`
	PaxID  int32 `gorm:"column:pax_id;primaryKey" json:"pax_id"`
}

// TableName TripPax's table name
func (*TripPax) TableName() string {
	return TableNameTripPax
}
